PREFIX dbpedia: <http://dbpedia.org/ontology/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX dbprop: <http://dbpedia.org/property/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX geoes: <http://geo.linkeddata.es/ontology/> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX owl: <http://www.w3.org/2002/07/owl#>  

SELECT ?member ?name ?country WHERE {
#  SERVICE <http://dbpedia.org/sparql> {
#         ?country <http://dbpedia.org/property/capital> <http://dbpedia.org/resource/Madrid> . }
#	SERVICE <http://mappingpedia.linkeddata.es/mappings/fusiontables/1pQBGUqR_g-j1WQavu-Fi1wGS7jsdRxomGc0DxMI/oegmembers.ttl> {
		?member rdf:type foaf:Person .
		?member foaf:name ?name .
		?member <http://dbpedia.org/ontology/Country> ?country .  
#	} 
} 
